### ISSUE TITLE
Finish the hub page

### ISSUE THREAD

**Issue by matboivin** [aurelien-brabant/ft_transcendance#100]
- Implement some layout (grid?) with the current games on which the User can click in order to watch it
- Finish the layout for the matchmaking system

**Comment by matboivin** [comment]
The test placeholders must be removed.

![Screenshot at 2022-05-15 19-41-37](https://user-images.githubusercontent.com/41596925/168486491-fe1477fe-9332-4f73-ad48-903756ec3e9a.png)

**Comment by Nnevalti** [comment]
Test placeholder has been removed.
Need to make further test but final version is almost done

**Comment by matboivin** [comment]
Perfect!
