### ISSUE TITLE
Populate achievements on achievement module init

### ISSUE THREAD

**Issue by aurelien-brabant** [aurelien-brabant/ft_transcendance#115]
We want the achievements to be populated in database when the achievement module is initialized.
For that we will use [NestJS's lifecycle events](https://docs.nestjs.com/fundamentals/lifecycle-events#lifecycle-events).

**Note:** we obviously don't want to duplicate achievements on each run. We only want to populate those that aren't already in database.

**Comment by matboivin** [comment]
Fixed by #143
