### ISSUE TITLE
User shouldn't be able to be friend with themselves

### ISSUE THREAD

**Issue by matboivin** [aurelien-brabant/ft_transcendance#141]
![Screenshot at 2022-05-02 15-51-16](https://user-images.githubusercontent.com/41596925/166271743-a849d5ea-6550-4e2e-8981-16c924a3c2e4.png)

**Comment by aurelien-brabant** [comment]
@busshi can you take care of this one? I'm not familiar with the friend logic and I think I may break something

**Comment by matboivin** [comment]
Taking it!
