### ISSUE TITLE
If friendship is deleted, duplicated card appears

### ISSUE THREAD

**Issue by matboivin** [aurelien-brabant/ft_transcendance#174]
On `master` branch:

![Screenshot at 2022-05-15 15-55-11](https://user-images.githubusercontent.com/41596925/168476551-a269e788-c136-47bf-8465-1da2bf40b698.png)

If user clicks on the left button to remove friend:

![Screenshot at 2022-05-15 15-55-48](https://user-images.githubusercontent.com/41596925/168476557-d55858e3-e87d-4b3d-bce7-3685f78d16f8.png)

**Comment by aurelien-brabant** [comment]
This should have been solved by the merge of #188
