### ISSUE TITLE
In sidebar, even if User is on another page, current page is always My profile

### ISSUE THREAD

**Issue by matboivin** [aurelien-brabant/ft_transcendance#176]
`My profile` background is darker whereas the user is on page `Play`.

`Play` should have the darker background.

![Screenshot at 2022-05-15 22-23-06](https://user-images.githubusercontent.com/41596925/168492435-f07c6743-1daa-407c-9b20-2778ca65c855.png)

**Comment by aurelien-brabant** [comment]
I saw this, but didn't document it. Thank you for doing so. I'm taking care of fixing it.
