### ISSUE TITLE
transcendance types are missing

### ISSUE THREAD

**Issue by aurelien-brabant** [aurelien-brabant/ft_transcendance#225]
See import list of `DirectMessage`, `DirectMessages`, `Group`
Missing types from transcendance types
- Channel
- DmMessage
- DmChannel

**Comment by matboivin** [comment]
It is weird, added them: https://github.com/aurelien-brabant/ft_transcendance/blob/2c244bace8186eb7284f5e6396025ca0852a58f6/src/nextjs-front/transcendance-types/index.d.ts#L88
