### ISSUE TITLE
fix build error on last PR

### ISSUE THREAD

**Issue by aurelien-brabant** [aurelien-brabant/ft_transcendance#51]
Looks like #50  don't build, according to the CI (which is apparently back, huray!)
See: https://app.circleci.com/pipelines/github/aurelien-brabant/ft_transcendance/82/workflows/80c57ef6-1947-4d47-ba0e-a182a894d7c2/jobs/67

**Comment by AstridDELCROS** [comment]
New commit to avoid rank issue:
https://github.com/aurelien-brabant/ft_transcendance/commits/blocked-users
Seems ok in docker 🤞
